services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  adminer:
    image: adminer  # Utilisation de l'image officielle Adminer
    ports:
      - "7080:8080"  # Expose Adminer sur le port 7080 de l'hôte
    environment:
      ADMINER_DB: ${POSTGRES_DB:-sae5}  # Nom de la base de données
      ADMINER_DRIVER: pgsql  # Type de base de données
      ADMINER_PASSWORD: ${POSTGRES_PASSWORD:-test}  # Mot de passe de la base de données
      ADMINER_SERVER: database  # Nom du service PostgreSQL dans docker-compose.yml
      ADMINER_USERNAME: ${POSTGRES_USER:-test}  # Nom d'utilisateur pour la base de données
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: This will be in the title!
  ###< symfony/mailer ###
