controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
semester_by_year:
    path: /api/semesters
    controller: App\Controller\SemesterController::getSemestersByYear
    methods: GET